import { useState, useEffect } from 'react'
import Head from 'next/head'
import Heading from '../../components/heading'
import Footer from '../../components/footer'
import MailingList from '../../components/mailingList'
import Subheading from '../../components/subheading'
import Navbar from '../../components/navbar'
import CardContainer from '../../components/blocks/cardContainer'
import Pagination from '../../components/pagination'
import classMockData from '../../constants/classMockData'

const HebrewCollection = () => {
  const [activePage, setActivePage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)
  const [itemsShown, setItemsShown] = useState([])
  const [itemsPerPage, setItemsPerPage] = useState(6)

  useEffect(() => {
    const newItemsShown = classMockData.slice(0, itemsPerPage)
    setItemsShown(newItemsShown)

    const newTotalPages = Math.ceil(classMockData.length / itemsPerPage)
    setTotalPages(newTotalPages)
  }, [])

  const updatePage = (newPage) => {
    setActivePage(newPage)
    //post request??

    const newItemsShown = classMockData.slice(
      itemsPerPage * (newPage - 1),
      itemsPerPage * newPage
    )
    setItemsShown(newItemsShown)
  }

  return (
    <div className="min-h-fullpage">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <header className="w-full">
        <Navbar />
      </header>
      <main>
        <Heading
          heading="Hebrew"
          breadcrumbs={[
            {
              link: '/',
              label: 'Home',
            },
            {
              link: '/events-classes',
              label: 'Events & Classes',
            },
            {
              link: '/events-classes/hebrew',
              label: 'Hebrew',
            },
          ]}
        />
        <div className="mb-12 sm:mt-6 overflow-hidden max-h-banner">
          <img
            src="/images/video.png"
            alt="customer suppport image"
            className="object-cover w-full h-auto min-h-banner"
          />
        </div>
        <h1
          className={`max-w-wrapper mx-auto md:px-0 text-2xl sm:text-3xl lg:text-4xl text-blue-850 text-center font-bold -mb-4 px-5`}
        >
          Hebrew interstitial page
        </h1>
        <Subheading
          content="Descriptive text about types of lessons"
          secondRow="students can find in collection."
        />
        <p className="text-center max-w-wrapper mx-auto px-5 leading-6 sm:text-base text-sm mb-4 -mt-6">
          Hebrew, the language of the Jewish people, is infused with culture and
          history. At American Jewish University, we deliver immersive Hebrew
          programs derived from the Israeli Ulpan methods. Our instructors are
          native speakers and dedicated to making Hebrew come alive for all
          learners. Regardless of your level or background, awaken your
          curiosity and dive{' '}
          <span className="whitespace-nowrap">into Hebrew at AJU.</span>
        </p>
        <p className="text-center max-w-wrapper mx-auto px-5 leading-6 sm:text-base text-sm lg:mb-12 sm:mb-7 -mb-2">
          Together, we will discover Hebrew, and the meaning of such words as
          sababa, yalla, and shtuyot!
        </p>
        <CardContainer schema={itemsShown} />
        <Pagination
          pages={Array.from(Array(totalPages + 1).keys()).slice(1)}
          activePage={activePage}
          updatePageProp={updatePage}
        />
      </main>
      <MailingList />
      <Footer />
    </div>
  )
}

export default HebrewCollection
