import Head from 'next/head'
import Link from 'next/link'

export default function SignUp() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="min-h-screen px-5 pt-16 lg:pt-20 bg-gray-50 pb-11 lg:pb-16 lg:px-0">
        <Link href="/">
          <a>
            <img
              src="/images/maven_logo2.png"
              alt="Maven logo"
              className="w-auto mx-auto h-14 sm:h-16"
            />
          </a>
        </Link>
        <div className="px-3 py-20 mx-auto bg-white rounded-sm max-w-register shadow-2 lg:max-w-6xl lg:py-28 lg:px-52 mt-11 lg:mt-16">
          <Link href="/register/individual">
            <a className="inline-block w-full py-6 mb-12 text-lg font-bold text-center text-white uppercase lg:py-8 lg:text-xl bg-blue-950 hover:opacity-80 focus:opacity-80 lg:mb-16">
              I want to register as an individual
            </a>
          </Link>
          <Link href="/register/organization">
            <a className="inline-block w-full py-6 text-lg font-bold text-center text-white uppercase lg:py-8 lg:text-xl bg-blue-950 hover:opacity-80 focus:opacity-80">
              I want to register as an organization
            </a>
          </Link>
        </div>
      </main>
    </>
  )
}
